controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

configs:
  clusterCredentials:
    talos-argocd-manager:
      server: https://kubernetes.default.svc
      labels:
        argocd.argoproj.io/auto-label-cluster-info: "true"
        argocd.argoproj.io/cluster-name: talos-argocd-manager
        argocd.argoproj.io/cluster-type: development
        argocd.argoproj.io/cluster-management: "true"
      config:
        tlsClientConfig:
        insecure: false
