apiVersion: v1
kind: Secret
metadata:
  name: argocd-demo-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/gravitek-io/argocd-demo.git

