apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  generators:
    - clusters:
        values:
          clusterVersion: '{{ metadata.labels.argocd.argoproj.io/kubernetes-version }}' # Kubernetes version : 1.26, 1.27, ...
          clusterType: '{{ metadata.labels.argocd.argoproj.io/cluster-type }}' # Kubernetes environment: development, production
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: 'cluster'
  template:
    metadata:
      name: '{{ name }}-helm-cert-manager'
      namespace: 'argocd'
    spec:
      project: 'default'
      destination:
        server: '{{ server }}'
        namespace: 'cert-manager'
      source:
        repoURL: 'https://github.com/rverchere/argocd-demo.git'
        targetRevision: 'HEAD'
        path: 'resources/helm-charts/versions/{{ values.clusterVersion }}/cert-manager/'
        helm:
          releaseName: 'cert-manager'
          valueFiles:
            - '../../../environments/{{ values.clusterType }}/cert-manager/custom-values.yaml'
            - '../../../clusters/{{ name }}/cert-manager/custom-values.yaml'
          ignoreMissingValueFiles: true
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=orphan
        - ServerSideApply=true

  syncPolicy:
    preserveResourcesOnDeletion: true
